# Site settings
title: Postcards for Zi
email: hello@chumak.io
description: > # this means to ignore newlines until "baseurl:"
  Hello Zi! I made this blog for you. I hope it will help us
  keep in touch while you’re over there and I’m over here!
  It’s a work in progress.
baseurl: "/postcards/" # the subpath of your site, e.g. /blog/
url: "http://towercap.github.io/" # the base hostname & protocol for your site
#twitter_username: towercap
#github_username: towercap

# Build settings
markdown: kramdown
excerpt_separator: <!--more-->
gems:
  - jemoji
